text_selection.settings:
  type: config_object
  mapping:
    text_selection_bg_color:
      type: string
      label: 'Background Color'
    text_selection_font_color:
      type: string
      label: 'Font Color'
